In [10]:
!pip install giotto-ph

Requirement already satisfied: giotto-ph in /usr/local/lib/python3.10/dist-packages (0.2.2)
Requirement already satisfied: numpy>=1.19.1 in /usr/local/lib/python3.10/dist-packages (from giotto-ph) (1.25.2)
Requirement already satisfied: scipy>=1.5.0 in /usr/local/lib/python3.10/dist-packages (from giotto-ph) (1.11.4)
Requirement already satisfied: scikit-learn>=0.23.1 in /usr/local/lib/python3.10/dist-packages (from giotto-ph) (1.2.2)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.23.1->giotto-ph) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.23.1->giotto-ph) (3.3.0)

In [11]:
import gph
import numpy as np

points = np.random.randint(20, size=(20, 2))
points

array([[ 9,  3],
       [ 1,  4],
       [ 3, 10],
       [ 7,  9],
       [11,  9],
       [11, 17],
       [10, 12],
       [12, 11],
       [ 1, 18],
       [ 0, 10],
       [18,  3],
       [18,  2],
       [ 3,  5],
       [ 4, 12],
       [ 4, 13],
       [13, 18],
       [ 4,  0],
       [ 5,  3],
       [11, 17],
       [16,  2]])

In [12]:
output = gph.ripser_parallel(points, return_generators=True)
output

{'dgms': [array([[0.       , 1.       ],
         [0.       , 1.       ],
         [0.       , 2.       ],
         [0.       , 2.236068 ],
         [0.       , 2.236068 ],
         [0.       , 2.236068 ],
         [0.       , 2.236068 ],
         [0.       , 2.236068 ],
         [0.       , 2.828427 ],
         [0.       , 3.       ],
         [0.       , 3.1622777],
         [0.       , 4.       ],
         [0.       , 4.       ],
         [0.       , 4.1231055],
         [0.       , 5.       ],
         [0.       , 5.0990195],
         [0.       , 5.8309517],
         [0.       , 7.071068 ],
         [0.       ,       inf]], dtype=float32),
  array([], shape=(0, 2), dtype=float32)],
 'gens': (array([[14, 14, 13],
         [11, 11, 10],
         [19, 19, 11],
         [ 5, 18, 15],
         [13, 13,  2],
         [12, 12,  1],
         [ 7,  7,  6],
         [ 6,  7,  4],
         [17, 17, 12],
         [ 9,  9,  2],
         [ 1, 17, 16],
         [16, 17,  0],
         [ 4,  4,  3],
         [ 3,  3,  2],
         [ 0, 12,  2],
         [15, 18,  6],
         [ 2, 14,  8],
         [10, 19,  0]]),
  [array([], shape=(0, 4), dtype=int64)],
  array([8]),
  [array([], shape=(0, 2), dtype=int64)])}

In [13]:
print("Persistance pairs: ")
print("H_0: ", output['dgms'][0])
print("H_1: ", output['dgms'][1])

Persistance pairs:
H_0:  [[0.        1.       ]
 [0.        1.       ]
 [0.        2.       ]
 [0.        2.236068 ]
 [0.        2.236068 ]
 [0.        2.236068 ]
 [0.        2.236068 ]
 [0.        2.236068 ]
 [0.        2.828427 ]
 [0.        3.       ]
 [0.        3.1622777]
 [0.        4.       ]
 [0.        4.       ]
 [0.        4.1231055]
 [0.        5.       ]
 [0.        5.0990195]
 [0.        5.8309517]
 [0.        7.071068 ]
 [0.              inf]]
H_1:  []

In [14]:
print(output['gens'][0])
print()
print(output['gens'][1])
print()
print(output['gens'][2])
print()
print(output['gens'][3])

[[14 14 13]
 [11 11 10]
 [19 19 11]
 [ 5 18 15]
 [13 13  2]
 [12 12  1]
 [ 7  7  6]
 [ 6  7  4]
 [17 17 12]
 [ 9  9  2]
 [ 1 17 16]
 [16 17  0]
 [ 4  4  3]
 [ 3  3  2]
 [ 0 12  2]
 [15 18  6]
 [ 2 14  8]
 [10 19  0]]

[array([], shape=(0, 4), dtype=int64)]

[8]

[array([], shape=(0, 2), dtype=int64)]

In [15]:
print("Generators for corresponding pairs: ")
print("H_0: ")
for i in range(len(output['gens'][0])):
  print(output['gens'][0][i][0], ' ---> ', output['gens'][0][i][1:])
print("first number is the 'birth' vertex, second and third number are vertices of the edge that `killed' the topological feature for all FINITE bars in H_0 barcode\n\n")
for i in range(len(output['gens'][2])):
  print(output['gens'][2][i], ' ---> +infty')
print("first number is the 'birth' vertex for all IN_FINITE bars in H_0 barcode")


print("\n ----------------------------")

for i in range(len(output['gens'][1][0])):
  print(output['gens'][1][0][i][:2], ' ---> ', output['gens'][1][0][i][2:])
print("first two numbers are  vertices of the edge that 'created' topological feature, third and forth numbers are vertices of the edge that `killed' the topological feature for all FINITE bars in H_1 barcode")
for i in range(len(output['gens'][3])):
  print(output['gens'][3][i], ' ---> +infty')
print("first two numbers are  vertices of the edge that 'created' topological feature for all IN_FINITE bars in H_1 barcode")

Generators for corresponding pairs:
H_0:
14  --->  [14 13]
11  --->  [11 10]
19  --->  [19 11]
5  --->  [18 15]
13  --->  [13  2]
12  --->  [12  1]
7  --->  [7 6]
6  --->  [7 4]
17  --->  [17 12]
9  --->  [9 2]
1  --->  [17 16]
16  --->  [17  0]
4  --->  [4 3]
3  --->  [3 2]
0  --->  [12  2]
15  --->  [18  6]
2  --->  [14  8]
10  --->  [19  0]
first number is the 'birth' vertex, second and third number are vertices of the edge that `killed' the topological feature for all FINITE bars in H_0 barcode


8  ---> +infty
first number is the 'birth' vertex for all IN_FINITE bars in H_0 barcode

 ----------------------------
first two numbers are  vertices of the edge that 'created' topological feature, third and forth numbers are vertices of the edge that `killed' the topological feature for all FINITE bars in H_1 barcode
[]  ---> +infty
first two numbers are  vertices of the edge that 'created' topological feature for all IN_FINITE bars in H_1 barcode

In [21]:
import numpy as np

H0_birth = np.zeros(points.shape[0], dtype=int)
H0_death = np.zeros((points.shape[0], 2), dtype=int)

H1_birth = np.zeros((points.shape[0], 2), dtype=int)
H1_death = np.zeros((points.shape[0], 2), dtype=int)

# Iterate over finite generators for H0
for i in range(len(output['gens'][0])):
    birth_vertex = output['gens'][0][i][0]
    death_vertices = output['gens'][0][i][1:]

    H0_birth[birth_vertex] = 1
    H0_death[death_vertices[0], 0] = 1
    H0_death[death_vertices[1], 1] = 1

# Iterate over finite generators for H0
for i in range(len(output['gens'][2])):
    birth_vertex = output['gens'][2][i]

    H0_birth[birth_vertex] = 1

# Iterate over finite generators for H1
for i in range(len(output['gens'][1][0][:2])):
    birth_vertices = output['gens'][1][0][i][:2]
    death_vertices = output['gens'][1][0][i][2:]

    H1_birth[birth_vertices[0], 0] = 1
    H1_birth[birth_vertices[1], 1] = 1
    H1_death[death_vertices[0], 0] = 1
    H1_death[death_vertices[1], 1] = 1

# Iterate over finite generators for H1
for i in range(len(output['gens'][3])):
    birth_vertices = output['gens'][3][i]
    if birth_vertices.size > 0:
        H1_birth[birth_vertices[0], 0] = 1
        H1_birth[birth_vertices[1], 1] = 1

In [22]:
import pandas as pd

# Assuming x_coords and y_coords are arrays containing x and y coordinates respectively
data = {'x': points[:, 0], 'y': points[:, 1]}

# Convert H0_birth, H0_death, H1_birth, H1_death to DataFrame
df_H0_birth = pd.DataFrame(H0_birth, columns=['H0_birth'])
df_H0_death = pd.DataFrame(H0_death, columns=['H0_death_1', 'H0_death_2'])
df_H1_birth = pd.DataFrame(H1_birth, columns=['H1_birth_1', 'H1_birth_2'])
df_H1_death = pd.DataFrame(H1_death, columns=['H1_death_1', 'H1_death_2'])

# Concatenate all DataFrames
df = pd.concat([pd.DataFrame(data), df_H0_birth, df_H0_death, df_H1_birth, df_H1_death], axis=1)

# Display the DataFrame
df

,x,y,H0_birth,H0_death_1,H0_death_2,H1_birth_1,H1_birth_2,H1_death_1,H1_death_2
0,9,3,1,0,1,0,0,0,0
1,1,4,1,0,1,0,0,0,0
2,3,10,1,0,1,0,0,0,0
3,7,9,1,1,1,0,0,0,0
4,11,9,1,1,1,0,0,0,0
5,11,17,1,0,0,0,0,0,0
6,10,12,1,0,1,0,0,0,0
7,12,11,1,1,0,0,0,0,0
8,1,18,1,0,1,0,0,0,0
9,0,10,1,1,0,0,0,0,0
10,18,3,1,0,1,0,0,0,0
11,18,2,1,1,1,0,0,0,0
12,3,5,1,1,1,0,0,0,0
13,4,12,1,1,1,0,0,0,0
14,4,13,1,1,0,0,0,0,0
15,13,18,1,0,1,0,0,0,0
16,4,0,1,0,1,0,0,0,0
17,5,3,1,1,0,0,0,0,0
18,11,17,0,1,0,0,0,0,0
19,16,2,1,1,0,0,0,0,0